### ISSUE TITLE
First pass controller functionality: S3BucketView

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ShioRamen#19]
## problem/context
(restated from [Brian's PR](https://github.com/RamenDR/ramen/pull/438)): If an ACM hub is not available to create a VRG to initiate PV recovery, is there a way to know which VRGs have been protected, given a S3 store profile?

A user could list the objects in a S3 bucket, but the Ramen object naming scheme is not meant to be an interface and is subject to change.

## current status
@hatfieldbrian created a PR for the API skeleton already here: https://github.com/RamenDR/ramen/pull/438

## objective
Build on the skeleton Brian provided and add MVP functionality to the controller.

## requirements
1. Get existing environment updated for Ramen development (some things are broken at head when re-creating from a fresh environment - debugging in process)
2. list backup names (get s3 list in S3BucketView reconciller, parse by namespaced name + vrg name, return list of valid names without content validation)
3. add annotations to vrg object that describes home cluster
4. add vrg to s3 store
5. filter backup names list by home cluster
6. unit testing/env testing

## sizing
1. fix development environment - 2 days
2. list backup names - 3 days
3. add annotations to vrg object that describes home cluster - TBD: discussed @hatfieldbrian  taking this part
4. add vrg to s3 store - TBD: discussed @hatfieldbrian taking this part
5. filter backup names list by home cluster - 1 day
6. unit testing/env testing - 5 days

**Comment by hatfieldbrian** [comment]
Bucket view support was merged in PR #43
