### ISSUE TITLE
S3BucketView update

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ShioRamen#21]
## Context
S3BucketView queries a S3 profile on a Managed Cluster, and returns a list of available backups on that cluster. The current design finds this information and stores it on the S3BucketView object's Status, along with a timestamp. If the timestamp field has been used (meaning that the timestamp field is not the default value), no further results are processed.

## Issue
What if users want to run this query multiple times?

## Potential Solutions
1. Current method: create a new object, or re-create the existing S3BucketView, to get updated results.
2. Alternative method: enable periodic S3 queries on the same object. An example implementation may be: add a field to S3BucketView.Spec to enable periodic lookup (e.g. "1m" for every 1 minute).

## Additional Comments
This was discussed briefly on 5/19/2022 before the S3BucketView initial implementation PR was created. It was decided that since there was no request for this functionality, it could be postponed. This Issue was created to document the discussion and the alternatives proposed, in the event that this changes in the future.

**Comment by hatfieldbrian** [comment]
@pdumbre requested this feature.  It is supported by the user deleting the status.  Support was merged into ShioRamen in PR #43
