### ISSUE TITLE
Provide a velero namespace name input - sprint 6

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ShioRamen#39]
Since ShioRamen is to be included in ODF, the driver for backup/restore should be OADP, rather than Velero. 

This issue was raised 7/19/2022 during the standup as a MVP requirement by Paul.

**Comment by hatfieldbrian** [comment]
I wonder which API the Velero driver must use?

It seems OADP supports the Velero API:

https://access.redhat.com/articles/5456281
> What APIs does the operator provide?
OADP provides the following APIs:
>- Backup
>- Restore
>- Schedule
>- BackupStorageLocation
>- VolumeSnapshotLocation
> 
> Red Hat has not added, removed or modified any of the APIs as documented in the Velero upstream project. The Velero site has more details on the [Velero API Types](https://velero.io/docs/main/api-types/).

**Comment by hatfieldbrian** [comment]
To support OADP, I suggest we provide an input in the ramen-dr-cluster-operator config map for the "velero" operator's namespace name and use this issue to track it.

**Comment by hatfieldbrian** [comment]
I think we need a default, and it should be "velero", but we need a PR to set it to OADP's namespace name by default for Fusion

**Comment by hatfieldbrian** [comment]
Fixed by #55
