### ISSUE TITLE
ProtectedVolumeReplicationGroupList API overwrites VRG metadata in case of failover

### ISSUE THREAD

**Issue by pdumbre** [RamenDR/ShioRamen#84]
For fusion, in case of failover, VRG gets created on surviving site with label 'metrodr.isf.ibm.com/status=relocated'.Observed that after failed site is up and running again, VRG metadata having this 'relocated' label is being overwritten with VRG metadata stored on earlier failed site..Due to this, relocated label which is part of VRG metadata is not preserved leading to issues in sync mechanism of fusion.

**Comment by hatfieldbrian** [comment]
@pdumbre Is the `KubeObjectProtection` feature enabled by the presence of said field in `VRG.Spec` ?

**Comment by hatfieldbrian** [comment]
As far as I know, `ProtectedVolumeReplicationGroupList` controller only writes to s3 store not k8s API server.  However, I suppose it is possible fusion controller is reading from it and writing read VRG Kube object labels to k8s API server.  Is the failover "from" site's VRG fenced from writing to s3 store(s) prior to failover?

**Comment by hatfieldbrian** [comment]
Closing ShioRamen issues.  Please reopen or if issue persists.
