### ISSUE TITLE
RamenDR operator pod in crash loop back state in DR use case when network disconnected between sites.

### ISSUE THREAD

**Issue by pdumbre** [RamenDR/ShioRamen#87]
Steps to reproduce:
1. Disconnect network between metrodr sites(sync DR)
2. Ramen DR pod in crashloop back state on both of the sites by throwing following exceptions related to 'protectedvolumereplicationgrouplist'

"VolumeReplicationGroup": "rackag3-app1-ns/rackag3-app1-ns", "State": "secondary"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x729a6e]

goroutine 787 [running]:
compress/gzip.(*Reader).Read(0x19, {0xc0003fe800, 0x28, 0xc0015ab258})
	/usr/local/go/src/compress/gzip/gunzip.go:247 +0x2e
encoding/json.(*Decoder).refill(0xc001708000)
	/usr/local/go/src/encoding/json/stream.go:165 +0x17f
encoding/json.(*Decoder).readValue(0xc001708000)
	/usr/local/go/src/encoding/json/stream.go:140 +0xbb
encoding/json.(*Decoder).Decode(0xc001708000, {0x1b542e0, 0xc001ac1400})
	/usr/local/go/src/encoding/json/stream.go:63 +0x78
github.com/ramendr/ramen/controllers.(*s3ObjectStore).DownloadObject(0xc00161ddc0, {0xc001ddd040, 0x4b}, {0x1b542e0, 0xc001ac1400})
	/workspace/controllers/s3utils.go:552 +0x625
github.com/ramendr/ramen/controllers.DownloadTypedObjects({0x1ed1778, 0xc00161ddc0}, {0xc000a68720, 0x2a}, {0x18375c0, 0xc001718840})
	/workspace/controllers/s3utils.go:467 +0x354
github.com/ramendr/ramen/controllers.DownloadVRGs(...)
	/workspace/controllers/s3utils.go:438
github.com/ramendr/ramen/controllers.(*ProtectedVolumeReplicationGroupListInstance).getVrgContentsFromS3(0xc0015abc00, {0xc000668800, 0x1f, 0x20}, {0x1ed1778, 0xc00161ddc0})
	/workspace/controllers/protectedvolumereplicationgrouplist_controller.go:151 +0x31a
github.com/ramendr/ramen/controllers.(*ProtectedVolumeReplicationGroupListReconciler).Reconcile(0xc00033b900, {0x1ed14d8, 0xc001581770}, {{{0x0, 0x1abc5c0}, {0xc0006474d0, 0x30}}})
	/workspace/controllers/protectedvolumereplicationgrouplist_controller.go:104 +0x61a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000756fd0, {0x1ed14d8, 0xc0015816e0}, {{{0x0, 0x1abc5c0}, {0xc0006474d0, 0x413b94}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000756fd0, {0x1ed1430, 0xc00033b880}, {0x19bcf40, 0xc00003bbe0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000756fd0, {0x1ed1430, 0xc00033b880})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x357

**Comment by hatfieldbrian** [comment]
Tracked by https://github.com/RamenDR/ramen/issues/843
